#pragma once

#include <string_view>

namespace mizcore {

enum class ERROR_TYPE
{
    SUCCESS = 0,
    UNKNOWN = 999,

    // Tokenizer and block parser errors
    BLOCK_NOT_CLOSED_IN_ARTICLE,
    BLOCK_NOT_IN_SECTION,
    CASE_BLOCK_NOT_UNDER_PROOF_BLOCK,
    CASE_BLOCK_PREV_SIBLING_NOT_CASE_BLOCK,
    DEFINITION_BLOCK_NOT_AFTER_BEGIN_KEYWORD,
    DEFINITION_BLOCK_NOT_JUST_BELOW_ROOT_BLOCK,
    END_KEYWORD_WITH_NO_PAIR_BLOCK,
    END_KEYWORD_WITHOUT_SEMICOLON,
    ENVIRON_KEYWORD_AFTER_BEGIN_KEYWORD,
    HEREBY_BLOCK_NOT_UNDER_PROOF_BLOCK,
    NOTATION_BLOCK_NOT_AFTER_BEGIN_KEYWORD,
    NOTATION_BLOCK_NOT_JUST_BELOW_ROOT_BLOCK,
    NOW_BLOCK_NOT_UNDER_PROOF_BLOCK,
    PER_CASES_STATEMENT_MISSING,
    PROOF_START_WITHOUT_PROPOSITION,
    REGISTRATION_BLOCK_NOT_AFTER_BEGIN_KEYWORD,
    REGISTRATION_BLOCK_NOT_JUST_BELOW_ROOT_BLOCK,
    ROOT_BLOCK_UNDER_BLOCK,
    SCHEME_BLOCK_NOT_AFTER_BEGIN_KEYWORD,
    SCHEME_BLOCK_NOT_JUST_BELOW_ROOT_BLOCK,
    STATEMENT_IS_EMPTY,
    STATEMENT_NOT_CLOSED_IN_ARTICLE,
    SUPPOSE_BLOCK_NOT_UNDER_PROOF_BLOCK,
    SUPPOSE_BLOCK_PREV_SIBLING_NOT_SUPPOSE_BLOCK,
    TOKEN_IS_UNKNOWN,
};

enum class ERROR_LEVEL
{
    ERROR,
    WARNING,
    INFO,
};

std::string_view
GetErrorMessage(ERROR_TYPE error);

int
GetErrorCode(ERROR_TYPE error);

ERROR_LEVEL
GetErrorLevel(ERROR_TYPE error);

std::string_view
GetErrorLevelText(ERROR_LEVEL level);

} // namespace mizcore
